services:
  db:
    image: postgres:18
    volumes: 
      - ./data/db:/var/lib/postgresql
    ports:
      - 5432:5432
    
    env_file:
      - .env
  
  adminer:
    image: adminer
    ports:
      - 8080:8080